// <auto-generated />
namespace Vidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class remove_required_status_for_genre_name : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remove_required_status_for_genre_name));
        
        string IMigrationMetadata.Id
        {
            get { return "202006300438052_remove_required_status_for_genre_name"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
